### ISSUE TITLE
Is app_requirements: "{{ app_directory }}/{{ app_name }}/requirements.txt" no good?

### ISSUE THREAD

**Issue by arvelt** [vitalk/ansible-flaskapp#5]
I use this book, but failed.

```
failed: [192.168.33.10] => {"cmd": "/home/vagrant/app/bin/pip install -r /home/vagrant/app/app/requirements.txt", "failed": true}
msg: stdout: Could not open requirements file: [Errno 2] No such file or directory: '/home/vagrant/app/app/requirements.txt'
Storing debug log for failure in /root/.pip/pip.log

#See /root/.pip/pip.log
------------------------------------------------------------
/home/vagrant/app/bin/pip run on Sun Jun 14 14:06:38 2015
Could not open requirements file: [Errno 2] No such file or directory: '/home/vagrant/app/app/requirements.txt'
Exception information:
Traceback (most recent call last):
  File "/home/vagrant/app/local/lib/python2.7/site-packages/pip/basecommand.py", line 122, in main
    status = self.run(options, args)
  File "/home/vagrant/app/local/lib/python2.7/site-packages/pip/commands/install.py", line 262, in run
    for req in parse_requirements(filename, finder=finder, options=options, session=session):
  File "/home/vagrant/app/local/lib/python2.7/site-packages/pip/req.py", line 1546, in parse_requirements
    session=session,
  File "/home/vagrant/app/local/lib/python2.7/site-packages/pip/download.py", line 278, in get_file_content
    raise InstallationError('Could not open requirements file: %s' % str(e))
InstallationError: Could not open requirements file: [Errno 2] No such file or directory: '/home/vagrant/app/app/requirements.txt'
```

`/home/vagrant/app/app/requirements.txt` made from `app_requirements: "{{ app_directory }}/{{ app_name }}/requirements.txt"`.
`/home/vagrant/app/requirements.txt` made from `git: repo={{ app_repository }} dest={{ app_directory }} version={{ app_version }} accept_hostkey=true`

You might want to write `app_requirements: "{{ app_directory }}/requirements.txt"` as default.

**Comment by vitalk** [comment]
Hi @arvelt.

You can always refine the `app_requirements` path according with your application layout:

``` ansible
- name: Deploy application
  hosts: app
  vars:
    app_requirements: "{{ app_directory }}/requirements.txt"

  roles:
    - vitalk.flaskapp
```

And yes, `{{ app_directory }}/requirements.txt` looks more sane default. Thank you!
